services:
  app:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - './app:/app'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IN_DEPLOYMENT: "false"
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - postgres_backend
  postgres_backend:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: aap_backend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  postgres_data: