services:
  api:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    build:
      context: .
      dockerfile: Dockerfile
      args:
        IN_DEPLOYMENT: "true"
    env_file: .env
    ports:
      - 80:8000