"""Added role to user model

Revision ID: fa39752f503d
Revises: e5ea629c35a5
Create Date: 2022-04-10 20:20:13.006135

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fa39752f503d"
down_revision = "e5ea629c35a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
